AWM_Restaurant/AWM_Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include(('table_mgmt.urls', 'table_mgmt'), namespace='table_mgmt')),
    path('portal/', include('portal.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.logout_view, name='logout_view'),
    path('', include('django.contrib.auth.urls')),
    path('restaurant/', include(('frontend.urls', 'frontend'), namespace='frontend')),
]

handler404 = 'table_mgmt.views.handle_page_not_found'

AWM_Restaurant/portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.portal_welcome, name='portal_welcome'),
]

AWM_Restaurant/table_mgmt/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('restaurantAdmin/', views.ResClass.ResManager(), name='restaurant_admin'),
    path('tables/cmenu/', views.createMenu, name='createMenu'),
    path('orders/c/<int:table>/', views.OrderClass.OrderManager(), name='createOrder'),
    path('orders/u/<int:order_id>/', views.OrderClass.OrderManager(), name='updateOrder'),

    # API path handler
    path('restaurant/login', views.LoginClass.LoginManager(), name='loginUser'),
    path('restaurant/createUser', views.UserClass.UserManager(), name='createUser'),
    path('restaurant/order', views.OrderClass.OrderManager(), name='Order'),
    path('restaurant/tables', views.TablesClass.TablesManager(), name='listTables'),
    path('restaurant/orders', views.OrdersClass.OrdersManager(), name='listOrders'),
    path('restaurant/waiters', views.WaitersClass.WaitersManager(), name='listWaiters'),
    path('restaurant/plates', views.PlatesClass.PlatesManager(), name='listPlates'),
    path('restaurant/table', views.TableClass.TableManager(), name='table'),

    # Api path handler mobile
    path('restaurant/csrftoken', views.get_csrf_token, name='getToken'),
    path('restaurant/m/order', views.mobile_order, name='mobileOrder'),
]

handler404 = 'table_mgmt.views.handle_page_not_found'

AWM_Restaurant/table_mgmt/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

# Create your models here.
class Table(models.Model):
    number = models.IntegerField(primary_key=True, validators=[MinValueValidator(0)])

    def __str__(self):
        return 'Table {}'.format(self.number)

class Menu(models.Model):
    code = models.AutoField(primary_key=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return 'Menu {}'.format(self.code)

    def save(self, *args, **kwargs):
        if not self.pk and Menu.objects.exists():
        # if you'll not check for self.pk
        # then error will also raised in update of exists model
            raise ValidationError('There is can be only one JuicerBaseSettings instance')
        return super(Menu, self).save(*args, **kwargs)

    def plates(self):
        return Plate.object.all()

class Plate(models.Model):
    code = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)

    # Day availability
    monday = models.BooleanField(default=False)
    tuesday = models.BooleanField(default=False)
    wednesday = models.BooleanField(default=False)
    thursday = models.BooleanField(default=False)
    friday = models.BooleanField(default=False)
    saturday = models.BooleanField(default=False)
    sunday = models.BooleanField(default=False)

    description = models.CharField(max_length=100)
    price = models.FloatField()
    available = models.BooleanField(default=True)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    # Proprietà piatto (vegan etc...)

    @property
    def days(self):
        "Returns the list of the days in which this plate is available"
        days_availability = []
        if self.monday:
            days_availability.append('Monday')
        if self.tuesday:
            days_availability.append('Tuesday')
        if self.wednesday:
            days_availability.append('Wednesday')
        if self.thursday:
            days_availability.append('Thursday')
        if self.friday:
            days_availability.append('Friday')
        if self.saturday:
            days_availability.append('Saturday')
        if self.sunday:
            days_availability.append('Sunday')

        return days_availability

    def __str__(self):
        return '{}'.format(self.name)

class Order(models.Model):
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    date = models.DateTimeField()
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client')
    waiter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='waiter')
    seats = models.IntegerField()
    plates = models.ManyToManyField(Plate, through='PlateDetails')
    password = models.CharField(max_length=100)

    class Meta:
        unique_together = (("table", "date"))

    def __str__(self):
        return 'Order {}'.format(self.id)

class PlateDetails(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    plate = models.ForeignKey(Plate, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

AWM_Restaurant/table_mgmt/forms.py
from django import forms
from .models import Table, Plate, Menu, Order
from django.contrib.auth.models import User

# definisco il form direttamente dal modello del tavolo
class MenuForm(forms.ModelForm):
    description = forms.CharField(max_length=100)

    class Meta:
        model = Menu
        fields = '__all__'

class TableForm(forms.ModelForm):
    number = forms.IntegerField(min_value=0)
    class Meta:
        model = Table
        fields = '__all__'

class OrderForm(forms.ModelForm):

    # vorrei disabilitare il tavolo ma non ci sto riuscendo TODO
    # date = forms.SplitDateTimeField()
    # password = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = Order
        fields = '__all__'
        exclude = ['plates',]

class PlateForm(forms.ModelForm):
    class Meta:
        model = Plate
        fields = '__all__'

AWM_Restaurant/table_mgmt/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotAllowed, JsonResponse
from django.contrib.auth.decorators import permission_required
from django.middleware.csrf import get_token
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

import json

from .models import *
from .forms import *
from .serializers import *
from .viewsClass import OrderClass, OrdersClass, TableClass, TablesClass, ResClass, PlatesClass, WaitersClass, UserClass, LoginClass

def index(request):
    return HttpResponseRedirect('/restaurant')

def handle_page_not_found(request, exception):
    return HttpResponseRedirect('/restaurant')

@permission_required('table_mgmt.add_menu', raise_exception=True)
def createMenu(request):
    if request.method == 'POST':
        menuForm = MenuForm(request.POST)
        if menuForm.is_valid():
            try:
                menuForm.save()
                return HttpResponseRedirect('/tables')
            except ValidationError:
                return render(request, 'table_mgmt/addMenu.html',{
                'form': menuForm,
                'title': 'Aggiungi tavolo',
                'content': "Aggiungi tavolo",
        })
        else:
            return HttpResponseRedirect('/tables/cmenu/')
    else:
        menuForm = MenuForm()
        return render(request, 'table_mgmt/addMenu.html', {
            'form': menuForm,
            'title': 'Aggiungi tavolo',
            'content': "Aggiungi tavolo",
        })

@permission_required('table_mgmt.add_table', raise_exception=True)
def addTable(request):
    if request.method == 'POST':
        tableForm = TableForm(request.POST)
        if tableForm.is_valid():
            tableForm.save()
            return HttpResponseRedirect('/tables')
        else:
            return HttpResponseRedirect('/tables/add/')
    else:
        tableForm = TableForm()
        return render(request, 'table_mgmt/addTable.html', {
            'form': tableForm,
            'title': 'Aggiungi tavolo',
            'content': "Aggiungi tavolo",
        })

@permission_required('table_mgmt.add_plate', raise_exception=True)
def addPlate(request):
    if request.method == 'POST':
        plate = PlateForm(request.POST)
        if plate.is_valid():
            plate.save()
            return HttpResponseRedirect('/tables')
    else:
        plate = PlateForm()
        return render(request, 'table_mgmt/addPlate.html', {
            'form': plate,
        })

def get_csrf_token(request):
    if request.method == 'GET':
        return JsonResponse({'csrf_token' : get_token(request)})

@csrf_exempt
def mobile_order(request):
    if request.method == 'POST':
        # Retrieve jsonified data
        req_body = json.loads(request.body)

        order = Order.objects.get(password=req_body['orderCode'])
        if order:
            """
            plates = []
            for plate in order.plates.all():
                plates.append(PlateSerializer(plate).data)

            resp = {
                'resp': "Your Order has been successfully been retrieved!",
                'plates': plates,
            }
            """

            serialized_order = OrderSerializer(order)
            resp = {
                'resp': 'Your order has been successfully been retrieved!',
                'order': serialized_order.data
            }
            return JsonResponse(resp)
        else:
            resp = {
                'resp': "Something wrong is happened! The selected order does't exists."
            }
            return JsonResponse(resp)

    elif request.method == 'PUT':
        """ UPDATE THE ORDER """
        # Retrieve jsonified data
        req_body = json.loads(request.body)
        resp = {}

        try:
            order = Order.objects.get(password=req_body['order_id'])
        except Order.DoesNotExist:
            resp = {
                'resp': "Something wrong is happened! The selected password does't exists."
            }
            return JsonResponse(resp)

        if req_body['plates'] and len(req_body['plates']) > 0:
            for plate_id, quantity in req_body['plates'].items():
                try:
                    plate = Plate.objects.get(code=plate_id)
                except Plate.DoesNotExist:
                    resp = {
                        'plate_id': plate_id
                    }
                platedetails = PlateDetails.objects.filter(plate=plate_id, order=order.id).first()
                if not platedetails:
                    order.plates.add(plate)
                    platedetails = PlateDetails.objects.get(plate=plate_id, order=order.id)
                platedetails.quantity += int(quantity)
                platedetails.save()
            order.save()
        resp = {
            'resp': "Your Order has been successfully updated!"
        }

        return JsonResponse(resp)

AWM_Restaurant/table_mgmt/templates/table_mgmt/addMenu.html
{% extends "base.html" %}

{% block content %}
Inserimento di un nuovo menu

<br />

{% if form.errors %}
	<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="POST">{% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Invia" />
</form>

{% endblock %}

AWM_Restaurant/table_mgmt/templates/table_mgmt/addPlate.html
{% extends "base.html" %}

{% block content %}
Inserimento di un nuovo piatto

<br />

<form method="POST">{% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Invia" />
</form>

{% endblock %}

AWM_Restaurant/table_mgmt/templates/table_mgmt/addTable.html
{% extends "base.html" %}


{% block content %}
Inserimento di un nuovo tavolo

<br />

<form method="POST">{% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Invia" />
</form>

{% endblock %}

AWM_Restaurant/table_mgmt/templates/table_mgmt/createOrder.html
{% extends "base.html" %}

{% block content %}
Inserimento di un nuovo ordine

<br />

<form method="{{ form_method }}">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Invia" />
</form>
{% endblock %}

AWM_Restaurant/table_mgmt/templates/table_mgmt/index.html
{% extends "base.html" %}

{% block title%}
Restaurant Login
{% endblock %}

{% block content %}
<header> <h1>Restaurant</h1> </header>
<section>
    <p>Welcome to Django Mysite. Please click <a href="/portal/">here</a> to log into our Web portal.</p>
</section>
{% endblock %}

AWM_Restaurant/table_mgmt/templates/table_mgmt/restaurant.html
{% extends "base.html" %}

{% block content %}
{{ content }}
<br />
<br />

Menu:
<br />
<ul>
    {% if menu.can_add %}
    <a href={% url 'table_mgmt:createMenu' %}>Aggiungi un menù</a>

    {% endif %}
{% if menu.can_view %}
        {% for m in menu.data %}
            <li>{{ m.description }}</li>
        {% endfor %}
    {% endif %}
</ul>



Tables:
<br />
<ul>
    {% if tables.can_add %}
    <a href={% url 'table_mgmt:tables' %}>Aggiungi un tavolo</a>
    {% endif %}

    {% if tables.can_view %}
        {% for table in tables.data %}
        <!-- Modify Table -->
        <li><a href={% url 'table_mgmt:createOrder' table=table.number %} title="Click to create a new order for this table" >Table {{ table.number }}</a></li>
        {% endfor %}
    {% endif %}
</ul>

Plates:
<br />
<ul>
    {% if plates.can_add %}
    <a href={% url 'table_mgmt:addPlate' %}>Aggiungi un piatto</a>

    {% endif %}
    {% if plates.can_view %}
        {% for plate in plates.data %}
            <li>'{{ plate.name }}' availability: {{ plate.days|join:", " }}</li>
        {% endfor %}
    {% endif %}
</ul>



Your orders:
<ul>
    {% if orders.can_view %}
        {% for order in orders.data %}
    <li><a href={% url 'table_mgmt:updateOrder' order_id=order.id %} title="Click to modify the order">Order {{ order.id }} </a> for table {{ order.table }}, created on {{ order.date }}<br />
        <ul>
            {% for plate in order.plates.all %}
                <li>{{plate.name}}</li>
            {% endfor %}
        </ul>
    </li>
        {% endfor %}
    {% endif %}
</ul>

{% endblock %}

AWM_Restaurant/table_mgmt/templates/table_mgmt/tables.html
{% extends "base.html" %}

{% block content %}
{{ content }}
<br />
<br />

Menu:
<br />
<ul>
    {% if menu.can_add %}
    <a href={% url 'table_mgmt:createMenu' %}>Aggiungi un menù</a>

    {% endif %}
{% if menu.can_view %}
        {% for m in menu.data %}
            <li>{{ m.description }}</li>
        {% endfor %}
    {% endif %}
</ul>



Tables:
<br />
<ul>
    {% if tables.can_add %}
    <a href={% url 'table_mgmt:addTable' %}>Aggiungi un tavolo</a>
    {% endif %}

    {% if tables.can_view %}
        {% for table in tables.data %}
    <li><a href={% url 'table_mgmt:createOrder' table=table.number %} title="Click to create a new order for this table" >Table {{ table.number }}</a></li>
        {% endfor %}
    {% endif %}
</ul>

Plates:
<br />
<ul>
    {% if plates.can_add %}
    <a href={% url 'table_mgmt:addPlate' %}>Aggiungi un piatto</a>

    {% endif %}
    {% if plates.can_view %}
        {% for plate in plates.data %}
            <li>'{{ plate.name }}' availability: {{ plate.days|join:", " }}</li>
        {% endfor %}
    {% endif %}
</ul>



Your orders:
<ul>
    {% if orders.can_add %}
    <a href={% url 'table_mgmt:createOrder' %}>Crea un nuovo ordine</a>
    {% endif %}
    {% if orders.can_view %}
        {% for order in orders.data %}
    <li><a href={% url 'table_mgmt:updateOrder' order_id=order.id target_hash=order.password %} title="Click to modify the order">Order {{ order.id }} </a> for table {{ order.table }}, created on {{ order.date }}<br />
        <ul>
            {% for plate in order.plates.all %}
                <li>{{plate.name}}</li>
            {% endfor %}
        </ul>
    </li>
        {% endfor %}
    {% endif %}
</ul>

{% endblock %}

AWM_Restaurant/table_mgmt/templates/table_mgmt/updateOrder.html
{% extends "base.html" %}

{% block content %}
Aggiorna il tuo ordine

<br />

<form method="PUT">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Invia" />
</form>

{% endblock %}